### ISSUE TITLE
Fix - fcm 토큰 문제

### ISSUE THREAD

**Issue by jun10920** [TrueEchoProject/TrueEcho_Main#151]
## ✅ Bug Report check list

- [x] 이슈 제목: Expo서버를 통해서 Fcm 알림 송신하기, 알람피드 조회 문제 해결하기

## BUG 개요

- 이런 버그가 있어
- ExpoPush Token으로도 fcm을 통해서 알림을 보내는 것이 가능했다가, 코드는 전혀 수정하지 않았는데 모종의 이유로 불가능해졌다.
- 
- 그래서 이런 문제가 있어
- 이런 식으로 재현이 돼
- 이 파일에서 문제가 발생한 거 같아

## TODO

- [ ] 이거 하려면 이런 걸 해야해
- [ ] 이것도 해야할 것 같아

**Comment by jun10920** [comment]
good
