### ISSUE TITLE
[Fix] - 좋아요 에러

### ISSUE THREAD

**Issue by HeeJohn** [TrueEchoProject/TrueEcho_Main#152]
## ✅ Bug Report check list

- [x] client emulator 로 확인.
- [x] postman  -> 배포서버로도 확인
- [x] postman  -> 로컬서버로도 확인.

## BUG 개요

- 좋아요를 누르면, 토글처럼 취소/추가가 반복되어야 하는데 추가할 때 에러가 터짐.
- 좋아요를 추가하면, 서버 오류 500이 발생.

## TODO

- [x] 에러가 정확히 뭔지 정의하기
- [x] 에러가 발생하는 이유 찾기
- [x] 에러가 발생하지 않도록 수정
- [x] 테스트
